Hit a compiler error C1001. (see details)
This is usually caused by the optimizer - which we're not using. So, the other culprit is probably the /bigobj flag. There's just simply too much to compile (in one .obj file). So, we're going to have to take the solution apart.